# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Development App "
client_id = "a68caa7216463cb1ce8cdfde6bf1c64e"
application_url = "https://nerve-manuals-offense-functional.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://nerve-manuals-offense-functional.trycloudflare.com/auth/callback",
  "https://nerve-manuals-offense-functional.trycloudflare.com/auth/shopify/callback",
  "https://nerve-manuals-offense-functional.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codingtest-goride.myshopify.com"
